# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: local
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  timescale-db:
    image: timescale/timescaledb:latest-pg16
    restart: always
    environment:
      POSTGRES_PASSWORD: local
    ports:
      - 5433:5432
    volumes:
      - ./timescale-data:/var/lib/postgresql/data
