stages:
  - test
  - build
  - deploy

.go-cache:
  variables:
    GOPATH: $CI_PROJECT_DIR/.go
  before_script:
    - mkdir -p .go
  cache:
    paths:
      - .go/pkg/mod/

format:
  image: golang:latest
  stage: test
  extends: .go-cache
  script:
    - go fmt $(go list ./... | grep -v /vendor/)
    - go vet $(go list ./... | grep -v /vendor/)
    - go test -race $(go list ./... | grep -v /vendor/)

compile:
  image: golang:latest
  extends: .go-cache
  stage: build
  script:
    - mkdir -p build
    - go build -o build ./...
  artifacts:
    paths:
      - build

deploy-server-1:
  tags:
    - couchdb-1
  stage: deploy
  only:
    - main
  dependencies:
    - compile
  script:
    - cp $ENV_FILE .env
    - cp .env timescale/
    - cd timescale
    - ./executeSql.sh
    - cd ..
    - ./deploy.sh

deploy-server-2:
  tags:
    - couchdb-2
  stage: deploy
  only:
    - main
  dependencies:
    - compile
  script:
    - cp $SERVER2_ENV_FILE .env
    - ./deploy.sh
