POST http://localhost:8080/journal
Content-Type: application/json

{
  "logs": "{\"_SOURCE_REALTIME_TIMESTAMP\":\"1723504380437713\",\"SYSLOG_TIMESTAMP\":\"2024-08-12T23:13:00.437669742Z\",\"_HOSTNAME\":\"couchdb-3\"}\n{\"_HOSTNAME\":\"couchdb-2\",\"_SOURCE_REALTIME_TIMESTAMP\":\"1723504381256471\"}"
}
